---
#- name: Include OS-specific variables.
#  include_vars: "{{ ansible_os_family }}.yml"

- include_vars: pf.yml
  when: ansible_os_family == 'FreeBSD' or  ansible_os_family == 'OpenBSD'

#- include_tasks: git.yml

- include_tasks: iptables.yml
  when: ansible_system == 'Linux'

- include_tasks: pf.yml
  when: ansible_os_family == 'FreeBSD' or ansible_os_family == 'OpenBSD'
