---
#- name: Include OS-specific variables.
#  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: git.yml

# Firewall
# Firewalld
- include_tasks: firewalld.yml
  when: ansible_os_family == 'RedHat'

# UFW
- include_tasks: ufw.yml
  when: ansible_os_family == 'Debian'
